# Generated by Django 4.1.7 on 2023-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopper_m',
            options={'permissions': [('can_access_supplier_admin', 'Can access supplier admin interface')]},
        ),
    ]
