# Generated by Django 4.1.7 on 2023-03-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_order_m_address'),
        ('user', '0001_initial'),
    ]

    operations = [

    ]
