# Generated by Django 4.1.7 on 2023-08-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0003_alter_supplier_m_options'),
        ('sale', '0009_ant_m_supplier'),
        ('user', '0003_alter_shopper_m_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_m',
            name='antly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback_m',
            name='product_ant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.ant_m'),
        ),
        migrations.AddField(
            model_name='feedback_m',
            name='product_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.other_m'),
        ),
        migrations.AddField(
            model_name='feedback_m',
            name='product_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.pack_m'),
        ),
        migrations.AddField(
            model_name='feedback_m',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_supplier.supplier_m'),
        ),
    ]
