# Generated by Django 4.1.7 on 2023-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address_m_adress_address_m_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_m',
            name='detail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
