# Generated by Django 4.1.7 on 2023-12-26 15:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_feedback_m_antly_feedback_m_product_ant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_m',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
