# Generated by Django 4.1.7 on 2023-03-24 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_shopper_m_address_address_m_shopper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('star', models.PositiveIntegerField(help_text='Veuillez attribuer une note entre 1 et 5.', validators=[django.core.validators.MinValueValidator(1, message='La note doit être supérieure ou égale à 1.'), django.core.validators.MaxValueValidator(5, message='La note doit être inférieure ou égale à 5.')])),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
