# Generated by Django 4.1.7 on 2023-03-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_feedback_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper_m',
            name='favorite_specie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
