# Generated by Django 4.1.7 on 2023-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_shopper_m_favorite_specie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper_m',
            name='product_purchased',
        ),
    ]
