# Generated by Django 4.1.7 on 2023-04-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_shopper_m_product_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address_m',
            name='shopper',
        ),
    ]
