# Generated by Django 4.1.7 on 2023-03-18 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_code', models.CharField(max_length=15, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nest_size', models.CharField(choices=[('Petit Plastique', 'small-plastic')], default='small-plastic', max_length=80)),
                ('problem', models.BooleanField(default=False)),
                ('thumbnail_nest', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_nest_1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_nest_2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('video_nest', models.FileField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=20000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('video', models.FileField(blank=True, null=True, upload_to='products')),
                ('problem', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker', models.CharField(choices=[('0', '0'), ('5', '5'), ('10', '10'), ('15', '15'), ('30', '30'), ('50', '50'), ('100', '100'), ('200', '200')], default='5', max_length=20)),
                ('gyne', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('10', '10'), ('+ 10', '+ 10')], default='1', max_length=20)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=120)),
                ('order_id', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductBaseAnt_m',
            fields=[
                ('product_m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.product_m')),
                ('localisation', models.CharField(blank=True, choices=[('France', 'France'), ('Sud de la France', 'south  France'), ('Nord de la France', 'north France'), ('Italie', 'Italy'), ('Grèce', 'Greece'), ('Méditerranée', 'Mediteranean'), ('Espagne', 'Spain')], default='France', max_length=20)),
                ('spece', models.CharField(choices=[('Aphaenogaster', 'Aphaenogaster'), ('Crematogaster', 'Crematogaster'), ('Camponotus', 'Camponotus'), ('Formica', 'Formica'), ('Lasius', 'Lasius'), ('Messor', 'Messor'), ('Myrmica', 'Myrmica'), ('Solenopsis', 'Solenopsis'), ('Tapinoma', 'Tapinoma'), ('Temnothorax', 'Temnothorax'), ('Pheidole', 'Pheidole')], max_length=100)),
                ('under_spece', models.CharField(blank=True, max_length=100)),
            ],
            bases=('sale.product_m',),
        ),
        migrations.CreateModel(
            name='Ant_m',
            fields=[
                ('productbaseant_m_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='sale.productbaseant_m')),
                ('Pack', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='ant', to='sale.pack_m')),
            ],
            bases=('sale.productbaseant_m',),
        ),
    ]
