# Generated by Django 4.1.7 on 2023-06-08 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_code', models.CharField(max_length=15, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('order_track', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pack_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=3000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('thumbnail_4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('video', models.FileField(blank=True, null=True, upload_to='products')),
                ('problem', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker', models.CharField(choices=[('0', '0'), ('5', '5'), ('10', '10'), ('15', '15'), ('30', '30'), ('50', '50'), ('100', '100'), ('200', '200')], default='5', max_length=20)),
                ('gyne', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('10', '10'), ('+ 10', '+ 10')], default='1', max_length=20)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ant_m',
            fields=[
                ('product_m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.product_m')),
                ('spece', models.CharField(choices=[('Acamatus', 'Acamatus'), ('Acanthognathus', 'Acanthognathus'), ('Acanthomyops', 'Acanthomyops'), ('Acanthostichus', 'Acanthostichus'), ('Acromyrmex', 'Acromyrmex'), ('Adetomyrma', 'Adetomyrma'), ('Aenictus', 'Aenictus'), ('Amblyopone', 'Amblyopone'), ('Amblyteles', 'Amblyteles'), ('Anergates', 'Anergates'), ('Anochetus', 'Anochetus'), ('Anonychomyrma', 'Anonychomyrma'), ('Aphaenogaster', 'Aphaenogaster'), ('Asphinctanilloides', 'Asphinctanilloides'), ('Atta', 'Atta'), ('Ateca', 'Ateca'), ('Brachymyrmex', 'Brachymyrmex'), ('Bothriomyrmex', 'Bothriomyrmex'), ('Camponotus', 'Camponotus'), ('Cardiocondyla', 'Cardiocondyla'), ('Carebara', 'Carebara'), ('Cephalotes', 'Cephalotes'), ('Cerapachys', 'Cerapachys'), ('Chelaner', 'Chelaner'), ('Cheliomyrmex', 'Cheliomyrmex'), ('Colobopsis', 'Colobopsis'), ('Crematogaster', 'Crematogaster'), ('Cryptocerus', 'Cryptocerus'), ('Cyphomyrmex', 'Cyphomyrmex'), ('Daceton', 'Daceton'), ('Diacamma', 'Diacamma'), ('Dinoponera', 'Dinoponera'), ('Diplomorium', 'Diplomorium'), ('Discothyrea', 'Discothyrea'), ('Dolichoderus', 'Dolichoderus'), ('Donisthorpea', 'Donisthorpea'), ('Dorymyrmex', 'Dorymyrmex'), ('Dorylus', 'Dorylus'), ('Eciton', 'Eciton'), ('Ectatomma', 'Ectatomma'), ('Ephebomyrmex', 'Ephebomyrmex'), ('Epoecus', 'Epoecus'), ('Epipheidole', 'Epipheidole'), ('Erebomyrma', 'Erebomyrma'), ('Euponera', 'Euponera'), ('Forelius', 'Forelius'), ('Formica', 'Formica'), ('Formicoxenus', 'Formicoxenus'), ('Gigantiops', 'Gigantiops'), ('Harpagoxenus', 'Harpagoxenus'), ('Harpegnathos', 'Harpegnathos'), ('Holcoponera', 'Holcoponera'), ('Hypoclinea', 'Hypoclinea'), ('Hypoponera', 'Hypoponera'), ('Ichnomyrmex', 'Ichnomyrmex'), ('Iridomyrmex', 'Iridomyrmex'), ('Janetia ', 'Janetia '), ('Lasius', 'Lasius'), ('Leptanilloides', 'Leptanilloides'), ('Leptogenys', 'Leptogenys'), ('Leptomyrmex', 'Leptomyrmex'), ('Leptothorax', 'Leptothorax'), ('Linepithema', 'Linepithema'), ('Liometopum', 'Liometopum'), ('Lobopelta', 'Lobopelta'), ('Macromischa', 'Macromischa'), ('Manica', 'Manica'), ('Megaponera', 'Megaponera'), ('Melophorus', 'Melophorus'), ('Messor', 'Messor'), ('Monomorium', 'Monomorium'), ('Myrmecia', 'Myrmecia'), ('Myrmecina', 'Myrmecina'), ('Myrmecocystus', 'Myrmecocystus'), ('Myrmelachista', 'Myrmelachista'), ('Myrmica', 'Myrmica'), ('Mystrium', 'Mystrium'), ('Neivamyrmex', 'Neivamyrmex'), ('Neoponera', 'Neoponera'), ('Notoncus', 'Notoncus'), ('Odontomachus', 'Odontomachus'), ('Oecophylla', 'Oecophylla'), ('Pachycondyla', 'Pachycondyla'), ('Paraponera', 'Paraponera'), ('Parasyscia', 'Parasyscia'), ('Paratrechina', 'Paratrechina'), ('Peronomyrmex', 'Peronomyrmex'), ('Pheidole', 'Pheidole'), ('Pheidologeton', 'Pheidologeton'), ('Pismire', 'Pismire'), ('Plagiolepis', 'Plagiolepis'), ('Platythyrea', 'Platythyrea'), ('Pogonomyrmex', 'Pogonomyrmex'), ('Polyergus', 'Polyergus'), ('Ponera', 'Ponera'), ('Prenolepis', 'Prenolepis'), ('Proceratium', 'Proceratium'), ('Pseudomyrma', 'Pseudomyrma'), ('Pseudomyrmex', 'Pseudomyrmex'), ('Quartina', 'Quartina'), ('Rhytidoponera', 'Rhytidoponera'), ('Rogeria', 'Rogeria'), ('Solenopsis', 'Solenopsis'), ('Stenamma', 'Stenamma'), ('Stigmatomma', 'Stigmatomma'), ('Streblognathus', 'Streblognathus'), ('Strongylognathus', 'Strongylognathus'), ('Strumigenys', 'Strumigenys'), ('Sympheidole', 'Sympheidole'), ('Sysphincta', 'Sysphincta'), ('Tapinoma', 'Tapinoma'), ('Technomyrmex', 'Technomyrmex'), ('Temnothorax', 'Temnothorax'), ('Tetramorium', 'Tetramorium'), ('Tetraogmus', 'Tetraogmus'), ('Typhlomyrmex', 'Typhlomyrmex'), ('Tyrannomyrmex', 'Tyrannomyrmex'), ('Wheeleriella', 'Wheeleriella'), ('Wasmannia', 'Wasmannia'), ('Xenomyrmex', 'Xenomyrmex'), ('Xiphomyrmex', 'Xiphomyrmex')], max_length=100)),
                ('under_spece', models.CharField(blank=True, max_length=100)),
            ],
            bases=('sale.product_m',),
        ),
        migrations.CreateModel(
            name='Other_m',
            fields=[
                ('product_m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.product_m')),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(blank=True, choices=[('nid', 'nid'), ('accessoire', 'accessoire'), ('nourriture', 'nourriture'), ('matériaux', 'materiaux')], default='accessoire', max_length=50)),
            ],
            bases=('sale.product_m',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sale.order_m')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
