# Generated by Django 4.1.7 on 2023-03-20 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_m',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address_m'),
        ),
        migrations.AddField(
            model_name='order_m',
            name='items',
            field=models.ManyToManyField(to='sale.orderitem_m'),
        ),
        migrations.AddField(
            model_name='order_m',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem_m',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem_m',
            name='pack',
            field=models.ManyToManyField(to='sale.pack_m'),
        ),
        migrations.AddField(
            model_name='orderitem_m',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.productbaseant_m'),
        ),
        migrations.AddField(
            model_name='orderitem_m',
            name='size',
            field=models.ManyToManyField(to='sale.size_m'),
        ),
        migrations.AddField(
            model_name='pack_m',
            name='size',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.size_m'),
        ),
        migrations.AddField(
            model_name='size_m',
            name='product_base',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='sale.productbaseant_m'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ant_m',
            name='Pack',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ant', to='sale.pack_m'),
        ),
        migrations.AlterField(
            model_name='pack_m',
            name='nest_size',
            field=models.CharField(choices=[('Petit Plexi', 'small-plastic'), ('Moyen Plexi', 'medium-plastic'), ('Grand Plexi', 'big-plastic')], default='small-plastic', max_length=80),
        ),
        migrations.AlterField(
            model_name='productbaseant_m',
            name='localisation',
            field=models.CharField(blank=True, choices=[("Afrique de l'Est", 'East Africa'), ("Afrique de l'Ouest", 'West Africa'), ('Afrique du Nord', 'North Africa'), ('Algérie', 'Algeria'), ('Australie', 'Australia'), ('Bangladesh', 'Bangladesh'), ('Belgique', 'Belgium'), ('Bhoutan', 'Bhutan'), ('Brunei', 'Brunei'), ('Burundi', 'Burundi'), ('Cambodge', 'Cambodia'), ('Chine', 'China'), ('Comores', 'Comoros'), ('Corée', 'Korea'), ('Corse', 'Corsica'), ("Côte d'Ivoire", 'Ivory Coast'), ('Espagne', 'Spain'), ('Émirats Arabes Unis', 'United Arab Emirates'), ('Égypte', 'Egypt'), ('Éthiopie', 'Ethiopia'), ('Europe Centrale', 'Central Europe'), ("Europe de l'Est", 'Eastern Europe'), ("Europe de l'Ouest", 'Western Europe'), ('Europe du Nord', 'Northern Europe'), ('Europe du Sud-Est', 'Southeastern Europe'), ('France', 'France'), ('Gambie', 'Gambia'), ('Ghana', 'Ghana'), ('Grèce', 'Greece'), ('Inde', 'India'), ('Indonésie', 'Indonesia'), ('Iran', 'Iran'), ('Irak', 'Iraq'), ('Irlande', 'Ireland'), ('Israël', 'Israel'), ('Italie', 'Italy'), ('Japon', 'Japan'), ('Jordanie', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Laos', 'Laos'), ('Liban', 'Lebanon'), ('Liberia', 'Liberia'), ('Libye', 'Libya'), ('Luxembourg', 'Luxembourg'), ('Madagascar', 'Madagascar'), ('Malaisie', 'Malaysia'), ('Maroc', 'Morocco'), ('Mauritanie', 'Mauritania'), ('Méditerranée', 'Mediterranean'), ('Mongolie', 'Mongolia'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Népal', 'Nepal'), ('Nigeria', 'Nigeria'), ('Nord de la France', 'North France'), ('Nouvelle-Zélande', 'New Zealand'), ('Océan Indien', 'Indian Ocean'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Papouasie-Nouvelle-Guinée', 'Papua New Guinea'), ('Philippines', 'Philippines'), ('Polynésie française', 'French Polynesia'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Russie', 'Russia'), ('Rwanda', 'Rwanda'), ('Samoa', 'Samoa'), ('Scandinavie', 'Scandinavia'), ('Sénégal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sicile', 'Sicily'), ('Sierra Leone', 'Sierra Leone'), ('Singapour', 'Singapore'), ('Soudan', 'Sudan'), ('Sri Lanka', 'Sri Lanka'), ('Sud de la France', 'South France'), ('Suisse', 'Switzerland'), ('Syrie', 'Syria'), ('Tadjikistan', 'Tajikistan'), ('Tanzanie', 'Tanzania'), ('Thaïlande', 'Thailand'), ('Timor Oriental', 'East Timor'), ('Togo', 'Togo'), ('Tunisie', 'Tunisia'), ('Turkménistan', 'Turkmenistan'), ('Turquie', 'Turkey'), ('Ukraine', 'Ukraine'), ('Union Européenne', 'European Union'), ('Uruguay', 'Uruguay'), ('Vanuatu', 'Vanuatu'), ('Vatican', 'Vatican'), ('Venezuela', 'Venezuela'), ('Viêt Nam', 'Vietnam'), ('Yémen', 'Yemen'), ('Zambie', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], default='France', max_length=50),
        ),
        migrations.AlterField(
            model_name='productbaseant_m',
            name='spece',
            field=models.CharField(choices=[('Acamatus', 'Acamatus'), ('Acanthognathus', 'Acanthognathus'), ('Acanthomyops', 'Acanthomyops'), ('Acanthostichus', 'Acanthostichus'), ('Acromyrmex', 'Acromyrmex'), ('Adetomyrma', 'Adetomyrma'), ('Aenictus', 'Aenictus'), ('Amblyopone', 'Amblyopone'), ('Amblyteles', 'Amblyteles'), ('Anergates', 'Anergates'), ('Anochetus', 'Anochetus'), ('Anonychomyrma', 'Anonychomyrma'), ('Aphaenogaster', 'Aphaenogaster'), ('Asphinctanilloides', 'Asphinctanilloides'), ('Atta', 'Atta'), ('Ateca', 'Ateca'), ('Brachymyrmex', 'Brachymyrmex'), ('Bothriomyrmex', 'Bothriomyrmex'), ('Camponotus', 'Camponotus'), ('Cardiocondyla', 'Cardiocondyla'), ('Carebara', 'Carebara'), ('Cephalotes', 'Cephalotes'), ('Cerapachys', 'Cerapachys'), ('Chelaner', 'Chelaner'), ('Cheliomyrmex', 'Cheliomyrmex'), ('Colobopsis', 'Colobopsis'), ('Crematogaster', 'Crematogaster'), ('Cryptocerus', 'Cryptocerus'), ('Cyphomyrmex', 'Cyphomyrmex'), ('Daceton', 'Daceton'), ('Diacamma', 'Diacamma'), ('Dinoponera', 'Dinoponera'), ('Diplomorium', 'Diplomorium'), ('Discothyrea', 'Discothyrea'), ('Dolichoderus', 'Dolichoderus'), ('Donisthorpea', 'Donisthorpea'), ('Dorymyrmex', 'Dorymyrmex'), ('Dorylus', 'Dorylus'), ('Eciton', 'Eciton'), ('Ectatomma', 'Ectatomma'), ('Ephebomyrmex', 'Ephebomyrmex'), ('Epoecus', 'Epoecus'), ('Epipheidole', 'Epipheidole'), ('Erebomyrma', 'Erebomyrma'), ('Euponera', 'Euponera'), ('Forelius', 'Forelius'), ('Formica', 'Formica'), ('Formicoxenus', 'Formicoxenus'), ('Gigantiops', 'Gigantiops'), ('Harpagoxenus', 'Harpagoxenus'), ('Harpegnathos', 'Harpegnathos'), ('Holcoponera', 'Holcoponera'), ('Hypoclinea', 'Hypoclinea'), ('Hypoponera', 'Hypoponera'), ('Ichnomyrmex', 'Ichnomyrmex'), ('Iridomyrmex', 'Iridomyrmex'), ('Janetia ', 'Janetia '), ('Lasius', 'Lasius'), ('Leptanilloides', 'Leptanilloides'), ('Leptogenys', 'Leptogenys'), ('Leptomyrmex', 'Leptomyrmex'), ('Leptothorax', 'Leptothorax'), ('Linepithema', 'Linepithema'), ('Liometopum', 'Liometopum'), ('Lobopelta', 'Lobopelta'), ('Macromischa', 'Macromischa'), ('Manica', 'Manica'), ('Megaponera', 'Megaponera'), ('Melophorus', 'Melophorus'), ('Messor', 'Messor'), ('Monomorium', 'Monomorium'), ('Myrmecia', 'Myrmecia'), ('Myrmecina', 'Myrmecina'), ('Myrmecocystus', 'Myrmecocystus'), ('Myrmelachista', 'Myrmelachista'), ('Myrmica', 'Myrmica'), ('Mystrium', 'Mystrium'), ('Neivamyrmex', 'Neivamyrmex'), ('Neoponera', 'Neoponera'), ('Notoncus', 'Notoncus'), ('Odontomachus', 'Odontomachus'), ('Oecophylla', 'Oecophylla'), ('Pachycondyla', 'Pachycondyla'), ('Paraponera', 'Paraponera'), ('Parasyscia', 'Parasyscia'), ('Paratrechina', 'Paratrechina'), ('Peronomyrmex', 'Peronomyrmex'), ('Pheidole', 'Pheidole'), ('Pheidologeton', 'Pheidologeton'), ('Pismire', 'Pismire'), ('Plagiolepis', 'Plagiolepis'), ('Platythyrea', 'Platythyrea'), ('Pogonomyrmex', 'Pogonomyrmex'), ('Polyergus', 'Polyergus'), ('Ponera', 'Ponera'), ('Prenolepis', 'Prenolepis'), ('Proceratium', 'Proceratium'), ('Pseudomyrma', 'Pseudomyrma'), ('Pseudomyrmex', 'Pseudomyrmex'), ('Quartina', 'Quartina'), ('Rhytidoponera', 'Rhytidoponera'), ('Rogeria', 'Rogeria'), ('Solenopsis', 'Solenopsis'), ('Stenamma', 'Stenamma'), ('Stigmatomma', 'Stigmatomma'), ('Streblognathus', 'Streblognathus'), ('Strongylognathus', 'Strongylognathus'), ('Strumigenys', 'Strumigenys'), ('Sympheidole', 'Sympheidole'), ('Sysphincta', 'Sysphincta'), ('Tapinoma', 'Tapinoma'), ('Technomyrmex', 'Technomyrmex'), ('Temnothorax', 'Temnothorax'), ('Tetramorium', 'Tetramorium'), ('Tetraogmus', 'Tetraogmus'), ('Typhlomyrmex', 'Typhlomyrmex'), ('Tyrannomyrmex', 'Tyrannomyrmex'), ('Wheeleriella', 'Wheeleriella'), ('Wasmannia', 'Wasmannia'), ('Xenomyrmex', 'Xenomyrmex'), ('Xiphomyrmex', 'Xiphomyrmex')], max_length=100),
        ),
    ]
