# Generated by Django 4.1.7 on 2024-05-03 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('admin_supplier', '0002_initial'),
        ('sale', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shopper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='size_m',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='admin_supplier.supplier_m'),
        ),
        migrations.AddField(
            model_name='pack_m',
            name='size',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.size_m'),
        ),
        migrations.AddField(
            model_name='ordertrack_m',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.order_m'),
        ),
        migrations.AddField(
            model_name='orderitem_m',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='orderitem_m',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_m',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address_m'),
        ),
        migrations.AddField(
            model_name='order_m',
            name='items',
            field=models.ManyToManyField(to='sale.orderitem_m'),
        ),
        migrations.AddField(
            model_name='order_m',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='size_m',
            name='product_base',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='sale.ant_m'),
        ),
        migrations.AddField(
            model_name='pack_m',
            name='nest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack', to='sale.other_m'),
        ),
        migrations.AddField(
            model_name='other_m',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other', to='admin_supplier.supplier_m'),
        ),
        migrations.AddField(
            model_name='ant_m',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ant', to='admin_supplier.supplier_m'),
        ),
    ]
