# Generated by Django 4.1.7 on 2023-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_order_m_address_order_m_items_order_m_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem_m',
            name='pack',
            field=models.ManyToManyField(blank=True, null=True, to='sale.pack_m'),
        ),
    ]
