# Generated by Django 4.1.7 on 2023-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_m',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
