# Generated by Django 4.1.7 on 2023-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_orderitem_m_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem_m',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='orderitem_m',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
