# Generated by Django 4.1.7 on 2023-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_product_m_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ant_m',
            name='localisation',
            field=models.CharField(blank=True, choices=[("Afrique de l'Est", 'East Africa'), ("Afrique de l'Ouest", 'West Africa'), ('Afrique du Nord', 'North Africa'), ('Algérie', 'Algeria'), ('Australie', 'Australia'), ('Bangladesh', 'Bangladesh'), ('Belgique', 'Belgium'), ('Bhoutan', 'Bhutan'), ('Brunei', 'Brunei'), ('Burundi', 'Burundi'), ('Cambodge', 'Cambodia'), ('Chine', 'China'), ('Comores', 'Comoros'), ('Corée', 'Korea'), ('Corse', 'Corsica'), ("Côte d'Ivoire", 'Ivory Coast'), ('Espagne', 'Spain'), ('Émirats Arabes Unis', 'United Arab Emirates'), ('Égypte', 'Egypt'), ('Éthiopie', 'Ethiopia'), ('Europe Centrale', 'Central Europe'), ("Europe de l'Est", 'Eastern Europe'), ("Europe de l'Ouest", 'Western Europe'), ('Europe du Nord', 'Northern Europe'), ('Europe du Sud-Est', 'Southeastern Europe'), ('France', 'France'), ('Gambie', 'Gambia'), ('Ghana', 'Ghana'), ('Grèce', 'Greece'), ('Inde', 'India'), ('Indonésie', 'Indonesia'), ('Iran', 'Iran'), ('Irak', 'Iraq'), ('Irlande', 'Ireland'), ('Israël', 'Israel'), ('Italie', 'Italy'), ('Japon', 'Japan'), ('Jordanie', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Laos', 'Laos'), ('Liban', 'Lebanon'), ('Liberia', 'Liberia'), ('Libye', 'Libya'), ('Luxembourg', 'Luxembourg'), ('Madagascar', 'Madagascar'), ('Malaisie', 'Malaysia'), ('Maroc', 'Morocco'), ('Mauritanie', 'Mauritania'), ('Méditerranée', 'Mediterranean'), ('Mongolie', 'Mongolia'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Népal', 'Nepal'), ('Nigeria', 'Nigeria'), ('Nord de la France', 'North France'), ('Nouvelle-Zélande', 'New Zealand'), ('Océan Indien', 'Indian Ocean'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Papouasie-Nouvelle-Guinée', 'Papua New Guinea'), ('Philippines', 'Philippines'), ('Polynésie française', 'French Polynesia'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Russie', 'Russia'), ('Rwanda', 'Rwanda'), ('Samoa', 'Samoa'), ('Scandinavie', 'Scandinavia'), ('Sénégal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sicile', 'Sicily'), ('Sierra Leone', 'Sierra Leone'), ('Singapour', 'Singapore'), ('Soudan', 'Sudan'), ('Sri Lanka', 'Sri Lanka'), ('Sud de la France', 'South France'), ('Suisse', 'Switzerland'), ('Syrie', 'Syria'), ('Tadjikistan', 'Tajikistan'), ('Tanzanie', 'Tanzania'), ('Thaïlande', 'Thailand'), ('Timor Oriental', 'East Timor'), ('Togo', 'Togo'), ('Tunisie', 'Tunisia'), ('Turkménistan', 'Turkmenistan'), ('Turquie', 'Turkey'), ('Ukraine', 'Ukraine'), ('Union Européenne', 'European Union'), ('Uruguay', 'Uruguay'), ('Vanuatu', 'Vanuatu'), ('Vatican', 'Vatican'), ('Venezuela', 'Venezuela'), ('Viêt Nam', 'Vietnam'), ('Yémen', 'Yemen'), ('Zambie', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], default='France', max_length=50),
        ),
    ]
