# Generated by Django 4.1.7 on 2023-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_ant_m_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_m',
            name='shipping_type',
            field=models.CharField(choices=[('L', 'Lettre'), ('C', 'Colis')], default='C', max_length=2),
        ),
    ]
