# Generated by Django 4.1.7 on 2023-03-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_remove_orderitem_m_date_ordered_orderitem_m_price'),
    ]

    operations = [

    ]
