# Generated by Django 4.1.7 on 2023-04-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_order_m_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='token',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
