# Generated by Django 4.1.7 on 2023-04-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_remove_transaction_token_alter_transaction_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='profile',
            new_name='shopper',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
