# Generated by Django 4.1.7 on 2023-08-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0003_alter_supplier_m_options'),
        ('sale', '0006_other_m_supplier_size_m_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_m',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other', to='admin_supplier.supplier_m'),
        ),
        migrations.AlterField(
            model_name='size_m',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='admin_supplier.supplier_m'),
        ),
    ]
