# Generated by Django 4.1.7 on 2023-04-08 07:45
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_rename_profile_transaction_shopper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='sale.order_m'),
            preserve_default=False,
        ),
    ]
