# Generated by Django 4.1.7 on 2023-08-26 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_other_m_supplier_alter_size_m_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_m',
            name='order_track',
        ),
        migrations.CreateModel(
            name='OrderTrack_m',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_track', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.order_m')),
            ],
        ),
    ]
