# Generated by Django 4.1.7 on 2023-05-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_remove_transaction_order_id_transaction_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nest_m',
            fields=[
                ('product_m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.product_m')),
                ('nest_size', models.CharField(choices=[('Petit Plexi', 'small-plastic'), ('Moyen Plexi', 'medium-plastic'), ('Grand Plexi', 'big-plastic')], default='small-plastic', max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('sale.product_m',),
        ),
        migrations.AlterField(
            model_name='pack_m',
            name='size',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.size_m'),
        ),
        migrations.AlterField(
            model_name='size_m',
            name='worker',
            field=models.CharField(choices=[('0', '0'), ('1 à 5', '1/5'), ('6 à 10', '6/10'), ('11 à 15', '11/15'), ('16 à 30', '16/30'), ('31 à 50', '31/50'), ('51 à 100', '51/100'), ('100 à 200', '100 à 200'), ('plus de 200', '+ 200')], default='5', max_length=20),
        ),
    ]
