# Generated by Django 4.1.7 on 2023-08-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0003_alter_supplier_m_options'),
        ('sale', '0008_remove_order_m_order_track_ordertrack_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='ant_m',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ant', to='admin_supplier.supplier_m'),
        ),
    ]
