# Generated by Django 4.1.7 on 2023-12-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_alter_ant_m_spece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_m',
            name='shipping_type',
        ),
        migrations.AddField(
            model_name='order_m',
            name='delivery_option',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
