ant_species = [
    {"Specie": "Acromyrmex echinatior", "breeding_level": 1, "Size": True, "Color": True, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Acromyrmex versicolor", "breeding_level": 1, "Size": True, "Color": True, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Anoplolepis gracilipes", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Asia"},
    {"Specie": "Aphaenogaster fulva", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Aphaenogaster longiceps", "breeding_level": 3, "Size": True, "Color": True, "Activity": True,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Aphaenogaster rudis", "breeding_level": 3, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "North-America"},
    {"Specie": "Aphaenogaster subterranea", "breeding_level": 1, "Size": False, "Color": True, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Atta cephalotes", "breeding_level": 2, "Size": True, "Color": False, "Activity": True, "Nest": False,
     "Region": "South-America"},
    {"Specie": "Brachymyrmex depilis", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Brachyponera chinensis", "breeding_level": 3, "Size": True, "Color": True, "Activity": True,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Camponotus aethiops", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "Southern-Europe"},
    {"Specie": "Camponotus castaneus", "breeding_level": 1, "Size": False, "Color": True, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Camponotus chromaiodes", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Camponotus compressus", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": False, "Region": "Asia"},
    {"Specie": "Camponotus consobrinus", "breeding_level": 3, "Size": True, "Color": False, "Activity": False,
     "Nest": True, "Region": "Australia"},
    {"Specie": "Camponotus cruentatus", "breeding_level": 2, "Size": True, "Color": True, "Activity": False,
     "Nest": False, "Region": "Southern-Europe"},
    {"Specie": "Camponotus fallax", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Camponotus herculeanus", "breeding_level": 2, "Size": True, "Color": False, "Activity": False,
     "Nest": True, "Region": "Northern-Europe"},
    {"Specie": "Camponotus irritans", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Camponotus japonicus", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": False, "Region": "Asia"},
    {"Specie": "Camponotus laevigatus", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Camponotus ligniperda", "breeding_level": 2, "Size": False, "Color": True, "Activity": False,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Camponotus nearcticus", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Camponotus nigriceps", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "Australia"},
    {"Specie": "Camponotus pennsylvanicus", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Camponotus piceus", "breeding_level": 1, "Size": False, "Color": True, "Activity": True, "Nest": False,
     "Region": "Southern-Europe"},
    {"Specie": "Camponotus truncatus", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Camponotus variegatus", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Cardiocondyla elegans", "breeding_level": 2, "Size": True, "Color": False, "Activity": False,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Cataglyphis cursor", "breeding_level": 3, "Size": True, "Color": True, "Activity": True, "Nest": False,
     "Region": "Southern-Europe"},
    {"Specie": "Cataglyphis iberica", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Colobopsis truncata", "breeding_level": 2, "Size": True, "Color": False, "Activity": False,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Crematogaster ashmeadi", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Crematogaster auberti", "breeding_level": 2, "Size": True, "Color": True, "Activity": True,
     "Nest": False, "Region": "Europe"},
    {"Specie": "Crematogaster lineolata", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Crematogaster osakensis", "breeding_level": 3, "Size": True, "Color": False, "Activity": False,
     "Nest": False, "Region": "Asia"},
    {"Specie": "Crematogaster scutellaris", "breeding_level": 1, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "Southern-Europe"},
    {"Specie": "Dolichoderus quadripunctatus", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Dolichoderus scabridus", "breeding_level": 2, "Size": True, "Color": True, "Activity": False,
     "Nest": False, "Region": "Asia"},
    {"Specie": "Dolichoderus taschenbergi", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Dolichoderus thoracicus", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Ectomomyrmex javanus", "breeding_level": 1, "Size": False, "Color": True, "Activity": True,
     "Nest": False, "Region": "Asia"},
    {"Specie": "Formica argentea", "breeding_level": 3, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "North-America"},
    {"Specie": "Formica cinerea", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Formica cunicularia", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Formica exsecta", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Formica fusca", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Formica glacialis", "breeding_level": 2, "Size": True, "Color": False, "Activity": True, "Nest": False,
     "Region": "Southern-Europe"},
    {"Specie": "Formica integra", "breeding_level": 3, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "North-America"},
    {"Specie": "Formica japonica", "breeding_level": 1, "Size": False, "Color": True, "Activity": True, "Nest": True,
     "Region": "Asia"},
    {"Specie": "Formica lugubris", "breeding_level": 2, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Formica neogagates", "breeding_level": 3, "Size": True, "Color": False, "Activity": False,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Formica obscuripes", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Formica paralugubris", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Formica pratensis", "breeding_level": 3, "Size": True, "Color": False, "Activity": False, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Formica pressilabris", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Formica rufibarbis", "breeding_level": 2, "Size": False, "Color": True, "Activity": False, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Formica sanguinea", "breeding_level": 2, "Size": True, "Color": False, "Activity": False, "Nest": False,
     "Region": "Southern-Europe"},
    {"Specie": "Formica subsericea", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Harpagoxenus sublaevis", "breeding_level": 3, "Size": True, "Color": True, "Activity": True,
     "Nest": True, "Region": "Northern-Europe"},
    {"Specie": "Hypoponera punctatissima", "breeding_level": 2, "Size": True, "Color": True, "Activity": False,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Iridomyrmex bicknelli", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Australia"},
    {"Specie": "Iridomyrmex purpureus", "breeding_level": 1, "Size": False, "Color": True, "Activity": True,
     "Nest": False, "Region": "Australia"},
    {"Specie": "Lasius alienus", "breeding_level": 2, "Size": True, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Lasius claviger", "breeding_level": 3, "Size": True, "Color": False, "Activity": False, "Nest": True,
     "Region": "North-America"},
    {"Specie": "Lasius emarginatus", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Europe"},
    {"Specie": "Lasius flavus", "breeding_level": 1, "Size": True, "Color": False, "Activity": False, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Lasius fuliginosus", "breeding_level": 2, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Lasius grandis", "breeding_level": 1, "Size": True, "Color": False, "Activity": True, "Nest": False,
     "Region": "Southern-Europe"},
    {"Specie": "Lasius japonicus", "breeding_level": 3, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Asia"},
    {"Specie": "Lasius mixtus", "breeding_level": 2, "Size": True, "Color": False, "Activity": False, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Lasius neoniger", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "North-America"},
    {"Specie": "Lasius niger", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Lasius platythorax", "breeding_level": 2, "Size": True, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Lasius umbratus", "breeding_level": 3, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Leptothorax acervorum", "breeding_level": 2, "Size": False, "Color": True, "Activity": True,
     "Nest": True, "Region": "Africa"},
    {"Specie": "Leptothorax exilis", "breeding_level": 3, "Size": True, "Color": False, "Activity": False, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Leptothorax kutteri", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Leptothorax muscorum", "breeding_level": 2, "Size": True, "Color": False, "Activity": False,
     "Nest": True, "Region": "Northern-Europe"},
    {"Specie": "Linepithema humile", "breeding_level": 1, "Size": False, "Color": True, "Activity": True, "Nest": False,
     "Region": "South-America"},
    {"Specie": "Manica rubida", "breeding_level": 3, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Melophorus bagoti", "breeding_level": 2, "Size": False, "Color": True, "Activity": True, "Nest": False,
     "Region": "Australia"},
    {"Specie": "Messor barbarus", "breeding_level": 1, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Messor structor", "breeding_level": 1, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Messor capitatus", "breeding_level": 2, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Messor arenarius", "breeding_level": 2, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Messor bouvieri", "breeding_level": 2, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Monomorium floricola", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Monomorium minimum", "breeding_level": 3, "Size": True, "Color": False, "Activity": True, "Nest": False,
     "Region": "North-America"},
    {"Specie": "Monomorium pharaonis", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Africa"},
    {"Specie": "Myrmecia gulosa", "breeding_level": 3, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Australia"},
    {"Specie": "Myrmecia nigriceps", "breeding_level": 3, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Australia"},
    {"Specie": "Myrmecia pyriformis", "breeding_level": 3, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Australia"},
    {"Specie": "Myrmecina graminicola", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Myrmecocystus mexicanus", "breeding_level": 3, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Myrmica americana", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "North-America"},
    {"Specie": "Myrmica incompleta", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Myrmica karavajevi", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Asia"},
    {"Specie": "Myrmica kotokui", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Asia"},
    {"Specie": "Myrmica lobicornis", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Myrmica lonae", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Myrmica pinetorum", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Myrmica rubra", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Myrmica ruginodis", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Myrmica sabuleti", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Myrmica salina", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": False,
     "Region": "Northern-Europe"},
    {"Specie": "Myrmica scabrinodis", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Myrmica sulcinodis", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Myrmoteras iriodum", "breeding_level": 3, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Asia"},
    {"Specie": "Nothomyrmecia macrops", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": False, "Region": "Australia"},
    {"Specie": "Nylanderia flavipes", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Nylanderia vaga", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "North-America"},
    {"Specie": "Oecophylla smaragdina", "breeding_level": 2, "Size": True, "Color": True, "Activity": False,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Opisthopsis haddoni", "breeding_level": 2, "Size": True, "Color": True, "Activity": False, "Nest": True,
     "Region": "Australia"},
    {"Specie": "Pachycondyla rufipes", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": True, "Region": "Africa"},
    {"Specie": "Paraparatrechina sakurae", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Paratrechina longicornis", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Pheidole bicarinata", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Pheidole indica", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Asia"},
    {"Specie": "Pheidole jativa", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Pheidole megacephala", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Africa"},
    {"Specie": "Pheidole pallidula", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Europe du Sud"},
    {"Specie": "Pheidole pilifera", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "South-America"},
    {"Specie": "Pheidole teneriffana", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Plagiolepis pygmaea", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Southern-Europe"},
    {"Specie": "Plagiolepis vindobonensis", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": False, "Region": "Southern-Europe"},
    {"Specie": "Pogonomyrmex barbatus", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Pogonomyrmex californicus", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
     "Nest": False, "Region": "North-America"},
    {"Specie": "Polyergus rufescens", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": False, "Region": "Northern-Europe"},
    {"Specie": "Polyrhachis ammon", "breeding_level": 2, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Asia"},
    {"Specie": "Polyrhachis dives", "breeding_level": 2, "Size": True, "Color": True, "Activity": True, "Nest": True,
     "Region": "Asia"},
    {"Specie": "Ponera coarctata", "breeding_level": 3, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Northern-Europe"},
    {"Specie": "Prionopelta antillana", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Proformica longiseta", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Rhytidoponera metallica", "breeding_level": 3, "Size": True, "Color": True, "Activity": False,
     "Nest": True, "Region": "Australia"},
    {"Specie": "Solenopsis fugax", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Southern-Europe"},
    {"Specie": "Solenopsis geminata", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Solenopsis invicta", "breeding_level": 3, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "South-America"},
    {"Specie": "Solenopsis molesta", "breeding_level": 1, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "South-America"},
    {"Specie": "Stenamma debile", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "South-America"},
    {"Specie": "Strongylognathus testaceus", "breeding_level": 3, "Size": True, "Color": False, "Activity": True,
     "Nest": True, "Region": "South-America"},
    {"Specie": "Tapinoma melanocephalum", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Tapinoma sessile", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "North-America"},
    {"Specie": "Temnothorax crassispinus", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Temnothorax nylanderi", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Northern-Europe"},
    {"Specie": "Temnothorax unifasciatus", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Tetramorium atratulum", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Northern-Europe"},
    {"Specie": "Tetramorium bicarinatum", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "North-America"},
    {"Specie": "Tetramorium caespitum", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Northern-Europe"},
    {"Specie": "Tetramorium impurum", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Northern-Europe"},
    {"Specie": "Tetramorium indocile", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Tetramorium inerme", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Asia"},
    {"Specie": "Tetramorium semilaeve", "breeding_level": 1, "Size": False, "Color": False, "Activity": True,
     "Nest": True, "Region": "Southern-Europe"},
    {"Specie": "Trichomyrmex destructor", "breeding_level": 2, "Size": True, "Color": True, "Activity": False,
     "Nest": True, "Region": "Asia"},
    {"Specie": "Vollenhovia emeryi", "breeding_level": 2, "Size": False, "Color": False, "Activity": True, "Nest": True,
     "Region": "Asia"},
{"Specie": "Dorylus nigricans", "breeding_level": 3, "Size": True, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Megaponera analis", "breeding_level": 2, "Size": True, "Color": True, "Activity": True,
 "Nest": False, "Region": "Africa"},
{"Specie": "Camponotus maculatus", "breeding_level": 2, "Size": True, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Lepisiota capensis", "breeding_level": 2, "Size": False, "Color": True, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Crematogaster castanea", "breeding_level": 2, "Size": False, "Color": True, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Myrmicaria brunnea", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Tetraponera allaborans", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Carebara diversa", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Oecophylla longinoda", "breeding_level": 3, "Size": True, "Color": True, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Solenopsis saevissima", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Formica fusca", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Polyrhachis militaris", "breeding_level": 2, "Size": True, "Color": True, "Activity": True, "Nest": True,
 "Region": "Africa"},
{"Specie": "Pseudomyrmex gracilis", "breeding_level": 3, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Cardiocondyla mauritanica", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
{"Specie": "Leptothorax acervorum", "breeding_level": 2, "Size": False, "Color": False, "Activity": True,
 "Nest": True, "Region": "Africa"},
]



