# Generated by Django 4.1.7 on 2023-08-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier_m',
            options={'permissions': [('can_access_supplier_admin', 'Can access supplier admin interface')]},
        ),
    ]
