# Generated by Django 4.1.7 on 2023-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0002_alter_supplier_m_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier_m',
            options={},
        ),
    ]
