# Generated by Django 4.1.7 on 2023-12-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0003_alter_supplier_m_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_m',
            name='shipping_costs_parcel_supplier',
        ),
        migrations.AddField(
            model_name='supplier_m',
            name='country',
            field=models.CharField(choices=[('Algérie', 'Algeria'), ('Australie', 'Australia'), ('Bangladesh', 'Bangladesh'), ('Belgique', 'Belgium'), ('Bhoutan', 'Bhutan'), ('Brunei', 'Brunei'), ('Burundi', 'Burundi'), ('Cambodge', 'Cambodia'), ('Chine', 'China'), ('Comores', 'Comoros'), ('Corée', 'Korea'), ('Corse', 'Corsica'), ("Côte d'Ivoire", 'Ivory Coast'), ('Espagne', 'Spain'), ('Émirats Arabes Unis', 'United Arab Emirates'), ('Égypte', 'Egypt'), ('Éthiopie', 'Ethiopia'), ('France', 'France'), ('Gambie', 'Gambia'), ('Ghana', 'Ghana'), ('Grèce', 'Greece'), ('Inde', 'India'), ('Indonésie', 'Indonesia'), ('Iran', 'Iran'), ('Irak', 'Iraq'), ('Irlande', 'Ireland'), ('Israël', 'Israel'), ('Italie', 'Italy'), ('Japon', 'Japan'), ('Jordanie', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Laos', 'Laos'), ('Liban', 'Lebanon'), ('Liberia', 'Liberia'), ('Libye', 'Libya'), ('Luxembourg', 'Luxembourg'), ('Madagascar', 'Madagascar'), ('Malaisie', 'Malaysia'), ('Maroc', 'Morocco'), ('Mauritanie', 'Mauritania'), ('Méditerranée', 'Mediterranean'), ('Mongolie', 'Mongolia'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Népal', 'Nepal'), ('Nigeria', 'Nigeria'), ('Nord de la France', 'North France'), ('Nouvelle-Zélande', 'New Zealand'), ('Océan Indien', 'Indian Ocean'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Papouasie-Nouvelle-Guinée', 'Papua New Guinea'), ('Philippines', 'Philippines'), ('Polynésie française', 'French Polynesia'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Russie', 'Russia'), ('Rwanda', 'Rwanda'), ('Samoa', 'Samoa'), ('Scandinavie', 'Scandinavia'), ('Sénégal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sicile', 'Sicily'), ('Sierra Leone', 'Sierra Leone'), ('Singapour', 'Singapore'), ('Soudan', 'Sudan'), ('Sri Lanka', 'Sri Lanka'), ('Sud de la France', 'South France'), ('Suisse', 'Switzerland'), ('Syrie', 'Syria'), ('Tadjikistan', 'Tajikistan'), ('Tanzanie', 'Tanzania'), ('Thaïlande', 'Thailand'), ('Timor Oriental', 'East Timor'), ('Togo', 'Togo'), ('Tunisie', 'Tunisia'), ('Turkménistan', 'Turkmenistan'), ('Turquie', 'Turkey'), ('Ukraine', 'Ukraine'), ('Uruguay', 'Uruguay'), ('Vanuatu', 'Vanuatu')], default='1', max_length=25),
        ),
        migrations.AddField(
            model_name='supplier_m',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='supplier_m',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
