# Generated by Django 4.1.7 on 2023-12-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0003_alter_supplier_m_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_m',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='supplier_m',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
