


# Generated by Django 4.1.7 on 2023-12-25 10:05

from django.db import migrations, models
import django_countries.fields

COUNTRY_MAPPING = {
    "Algérie": "DZ",
    "France": "FR"
}

def transfer_country(apps, schema_editor):
    Supplier = apps.get_model('admin_supplier', 'supplier_m')
    for supplier in Supplier.objects.all():
        # Utilisation de la correspondance pour obtenir le code de pays ISO
        country_code = COUNTRY_MAPPING.get(supplier.country, "")  # Mettez une valeur par défaut si nécessaire
        supplier.country = country_code
        supplier.save()

class Migration(migrations.Migration):

    dependencies = [
        ('admin_supplier', '0004_remove_supplier_m_shipping_costs_parcel_supplier_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_country, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplier_m',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
